import React from "react";
import Head from "next/head";

const CustomHead = ({ title }) => {
  return (
    <Head>
      <title>{title} || Text Flow</title>
      <meta name="description" content="Generated by create next app" />
      <meta
        name="keyword"
        content="TextFlow, Messenger app, SqueakIT, Abu Shama, Full Stack, Next JS, imshama.com"
      />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default CustomHead;
